// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx2QgXSrQOWyAgWAarMPHlgmJI0-Q2-5s',
    appId: '1:60623769962:web:4ece813e3caddebd371513',
    messagingSenderId: '60623769962',
    projectId: 'consulta-fipe-34c79',
    authDomain: 'consulta-fipe-34c79.firebaseapp.com',
    storageBucket: 'consulta-fipe-34c79.appspot.com',
    measurementId: 'G-0F8G722MH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzHl32tzBxA2VXQ6HLqwdSRDLn0dd0vWo',
    appId: '1:60623769962:android:f89a59ccaa4f6e50371513',
    messagingSenderId: '60623769962',
    projectId: 'consulta-fipe-34c79',
    storageBucket: 'consulta-fipe-34c79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcwQNr27gVh12N0ZsWFOdqIT-azvkFv3U',
    appId: '1:60623769962:ios:af07a6dae095774b371513',
    messagingSenderId: '60623769962',
    projectId: 'consulta-fipe-34c79',
    storageBucket: 'consulta-fipe-34c79.appspot.com',
    iosClientId: '60623769962-31ngdfdatr94rlmr6it5hq9964mh9st5.apps.googleusercontent.com',
    iosBundleId: 'com.example.consultaFipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcwQNr27gVh12N0ZsWFOdqIT-azvkFv3U',
    appId: '1:60623769962:ios:2a14279b4b64dd82371513',
    messagingSenderId: '60623769962',
    projectId: 'consulta-fipe-34c79',
    storageBucket: 'consulta-fipe-34c79.appspot.com',
    iosClientId: '60623769962-co5ofn3cs7ekiiu6u1ql8ljk3oajod2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.consultaFipe.RunnerTests',
  );
}
